sudo: required
services:
    - docker

before_install:
    - docker build -t itsyrulnikov/udemy-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true itsyrulnikov/udemy-docker npm run test -- --coverage